sonar.projectKey=ms-gofiber
sonar.projectName=ms-gofiber
sonar.sources=cmd,external,handler,internal,pkg,router
sonar.tests=cmd,external,handler,internal,pkg,router
sonar.test.inclusions=cmd/**/*_test.go,external/**/*_test.go,handler/**/*_test.go,internal/**/*_test.go,pkg/**/*_test.go,router/**/*_test.go
sonar.exclusions=**/*_test.go
sonar.go.coverage.reportPaths=coverage.out
