sonar.projectKey=ms-gofiber
sonar.projectName=ms-gofiber
sonar.sources=.
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.exclusions=vendor/**,data/**,coverage.out
sonar.go.coverage.reportPaths=coverage.out
